# Generated by Django 6.0.5 on 2026-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('da', models.IntegerField(verbose_name='Domain Authority')),
                ('dr', models.IntegerField(verbose_name='Domain Rating')),
                ('traffic', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('link_type', models.CharField(default='Do-Follow', max_length=50)),
            ],
        ),
    ]
